unicef/etools-epd

- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/document-details/document-details.ts
[ch21265] PD details- Document Details component
> [ch21265] PD details- Document Details component

- src_ts/components/pages/interventions/intervention-tab-pages/common/models/intervention.types.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/details-overview/details-overview.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/details-overview/interventionOverview.models.ts
[ch21253]PD Details - Overview section component
> [ch21253]PD Details - Overview section component

- src_ts/components/app-shell/app-shell.ts
- src_ts/components/pages/interventions/intervention-tab-pages/common/styles/shared-styles-lit.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/gender-equity-rating/gender-equity-rating.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/unicef-details/unicef-details.ts
- src_ts/endpoints/endpoints-list.ts
- src_ts/redux/actions/common-data.ts
- src_ts/redux/reducers/common-data.ts
> Pd Details update

- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/geographical-coverage/geographical-coverage.ts
[ch21267] PD details - Geographical Coverage component
> [ch21267] PD details - Geographical Coverage component

- src_ts/components/pages/interventions/intervention-tab-pages/intervention-results/effective-and-efficient-programme-management/activity-dialog.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-results/effective-and-efficient-programme-management/effective-and-efficient-programme-management.ts
[ch21613] PD results - 'Effective and efficient programme management' component
> [ch21613] PD results - 'Effective and efficient programme management' component

- src_ts/components/pages/interventions/intervention-tab-pages/common/mixins/repeatable-data-sets-mixin.ts
> repeatable-data-sets-mixin

- src_ts/components/pages/interventions/intervention-tab-pages/intervention-timing/intervention-dates/intervention-dates.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-timing/intervention-dates/interventionDates.models.ts
[ch21601] PD timing - Programme Document Dates component
> [ch21601] PD timing - Programme Document Dates component

- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/amendments/add-amendment-dialog.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/amendments/pd-amendments.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-overview/intervention-overview.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-overview/monitoring-visits-list/monitoring-visits-list.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-results/results-structure/cp-output-level.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-results/results-structure/modals/add-ram-indicators.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-results/results-structure/modals/pd-output-dialog.ts
- src_ts/components/pages/interventions/intervention-tab-pages/utils/utils.ts
No import from outside intervention-tab-pages
> Fix imports

- src_ts/components/pages/interventions/intervention-tab-pages/common/mixins/component-base-mixin.ts
- src_ts/components/pages/interventions/intervention-tab-pages/common/mixins/data-mixin.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/document-details/document-details.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/geographical-coverage/geographical-coverage.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/partner-details/partner-details.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/technical-guidance-capacity/technical-guidance.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/amendments/add-amendment-dialog.ts
Move towards all components using the `data` and `originalData` properties
> Rename dataToSave to data, take agreements from redux

- src_ts/components/common/toast-notifications/toast-notification-helper.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/programmatic-visits/programmatic-visits.ts
> [ch21966]Programmatic visits updates

- src_ts/components/app-shell/app-theme.ts
[ch21619]PD timing - Reporting Requirements component
> [ch21619]PD timing - Reporting Requirements component

- src_ts/components/app-shell/app-shell.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/unicef-details/pdUnicefDetails.models.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-details/unicef-details/unicef-details.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/amendments/add-amendment-dialog.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/amendments/pd-amendments.models.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/amendments/pd-amendments.selectors.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/amendments/pd-amendments.ts
- src_ts/components/pages/interventions/intervention-tab-pages/intervention-management/fund-reservations/fund-reservations.ts
- src_ts/redux/actions/common-data.ts
- src_ts/redux/reducers/common-data.ts
Unicef details, Amendments updates
> Unicef details, Amendments updates

- src_ts/components/pages/interventions/intervention-tab-pages/common/mixins/repeatable-data-sets-mixin.ts
> repeatable-data-sets-mixin fix

- src_ts/components/app-shell/app-shell.ts
- src_ts/components/env-flags/environment-flags.ts
- src_ts/endpoints/endpoints-list.ts
- src_ts/redux/actions/common-data.ts
- src_ts/redux/reducers/common-data.ts
- src_ts/types/globals.ts
> [ch21961]Add Env flags

- src_ts/components/app-shell/app-shell.ts
[ch22099] Gender-equity-rating handle loading spinner
> [ch22099] Gender-equity-rating handle loading spinner

- src_ts/components/user/user-actions.ts
> [ch22140]Handle user login expired

- src_ts/components/app-shell/app-shell.ts
- src_ts/components/pages/interventions/list/list-dummy-data.ts
[ch22181] Gender-equity-rating tweaks/bk needs
> [ch22181] Gender-equity-rating tweaks/bk needs

- src_ts/components/app-shell/app-shell.ts
- src_ts/components/app-shell/menu/app-menu.ts
- src_ts/routing/component-lazy-load-config.ts
- src_ts/routing/routes.ts
[ch22225] Remove second entry from the left menu (Page Two)
> [ch22225] Remove second entry from the left menu (Page Two)

- src_ts/components/app-shell/app-shell.ts
- src_ts/redux/reducers/common-data.ts
[ch22186] Risks component tweaks/bk needs
> [ch22186] Risks component tweaks/bk needs

- src_ts/components/common/layout/filters/etools-filters.ts
[ch22233] Show loading spinner for Filter section
> [ch22233] Show loading spinner for Filter section

- src_ts/components/app-shell/app-shell.ts
- src_ts/config/config.ts
[ch22239] Drop-down search section is overlapped by app header
> [ch22239] Drop-down search section is overlapped by app header

- src_ts/components/app-shell/app-theme.ts
[ch22116] Dividers are invisible in PMP (style issue)
> [ch22116] Dividers are invisible in PMP (style issue)

- src_ts/components/app-shell/app-shell.ts
- src_ts/redux/reducers/common-data.ts
[ch22167]PD Management - Financial component tweaks/bk needs
> [ch22167]PD Management - Financial component tweaks/bk needs

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/list/filters.ts
[ch22503] Update intervention status (naming)
> [ch22503]Update intervention status (naming)

- src_ts/endpoints/endpoints-list.ts
> [ch22658]Agreements endpoint fix

- src_ts/endpoints/endpoints-list.ts
> [ch22658]fix endpoint

- src_ts/redux/actions/app.ts
> [ch22376]Fix intermittent - can not read subscribe of undefined

- src_ts/components/app-shell/app-shell.ts
- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/list/filters.ts
- src_ts/redux/reducers/common-data.ts
[ch22503] Update intervention status (Draft to Development)
> [ch22503] Update intervention status (Draft to Development)

- src_ts/components/app-shell/app-theme.ts
- src_ts/endpoints/endpoints-list.ts
> [ch22735]Change endpoint

- src_ts/components/pages/interventions/intervention-list.ts
[ch22745]Incorrect budget value displayed on list
> [ch22745]Incorrect budget value displayed on list

- src_ts/components/app-shell/header/page-header.ts
[ch22804]Display current user info in profile dialog
> [ch22804]Display current user info in profile dialog

- src_ts/redux/actions/common-data.ts
- src_ts/redux/reducers/common-data.ts
[ch22036] Handle requests to PRP from intervention-tab-pages
> [ch22036] Handle requests to PRP from intervention-tab-pages

- package-lock.json
- package.json
[ch22599] Intermittent: Scroll blocks in Unicef Sections list and user cannot see last option
> [ch22599] Intermittent: Scroll blocks in Unicef Sections list and user cannot see last option

- src_ts/components/pages/interventions/intervention-list.ts
[ch22751] Money values are not formatted everywhere
> [ch22751] Money values are not formatted everywhere

- package-lock.json
- package.json
- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/list/filters.ts
[ch22903] PD/SPD Type filter - load from backend
> [ch22903] PD/SPD Type filter - load from backend

- src_ts/components/pages/interventions/list/filters.ts
[ch22143] Update code that uses SSFA checks
> [ch22143] Replace SSFA labels

- package-lock.json
- package.json
[ch23035] Highlight editable rows on hover
> [ch23035] Highlight editable rows on hover

- src_ts/components/common/layout/filters/etools-filters.ts
- src_ts/components/pages/interventions/intervention-list.ts
ch23102] Filters unnecessary reload
> [ch23102] Filters unnecessary reload

- package-lock.json
- package.json
[ch22928]File type validation on etools-upload not working
> [ch22928]File type validation on etools-upload not working

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/list/filters.ts
[ch23109] Refreshing page after deselecting all status filters
> [ch23109] Refreshing page after deselecting all status filters

- src_ts/components/app-shell/header/countries-dropdown-styles.ts
> [ch23118]Selected country color should be the same as the items to the right

- src_ts/components/common/layout/filters/etools-filters.ts
- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/redux/reducers/common-data.ts
> [ch23047]Show only not hidden partners in filter

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/types/intervention.types.d.ts
[ch23125]Show 'Accepted/Sent to' on the interventions list
> [ch23125]Show 'Accepted/Sent to' on the interventions list

- package-lock.json
- package.json
[ch23150] Intermittent dropdown issues
> [ch23150] Intermittent dropdown issues

- polymer.json
- src_ts/components/app-shell/app-shell.ts
- src_ts/components/app-shell/header/page-header.ts
- src_ts/redux/reducers/active-language.ts
[ch23184] Prepare for localization
> [ch23184] Prepare for localization

- src_ts/components/app-shell/header/page-header.ts
[ch23380] Countries drop-down too close to languages drop-down
> [ch23380] Countries drop-down too close to languages drop-down

- src_ts/components/common/layout/filters/etools-filters.ts
> [ch22900]Stop spinning wheel of death and show toast

- package-lock.json
- package.json
> [ch23100]Update etools-dialog v

- src_ts/components/common/toast-notifications/etools-toast.ts
[ch23576] Format toast message
> [ch23576] Format toast message

- assets/i18n/en.json
[ch23811] Supply Agreement/ Add optional field 'Unicef Product’ Number'
> [ch23811] Supply Agreement/ Add optional field 'Unicef Product’ Number'

- assets/i18n/en.json
[ch23854] Placeholders tweaks and standardization
> [ch23854] Placeholders tweaks and standardization

- package-lock.json
- package.json
- src_ts/components/pages/interventions/intervention-list.ts
[ch23154] Expose etools-currency-mixin functionality in an es6 module also
> [ch23154] Expose etools-currency-mixin functionality in an es6 module also

- assets/i18n/en.json
- assets/i18n/ro.json
- src_ts/components/app-shell/menu/app-menu.ts
[ch23781] Add second language (romanian).
> [ch23781] Add second language (romanian).

- package-lock.json
- package.json
- src_ts/components/app-shell/app-theme.ts
[ch24038] Forms should be navigable using TAB
> [ch24038] Forms should be navigable using TAB

- src_ts/components/app-shell/app-shell.ts
[ch24285] Review tab is not rendered
> [ch24285] Review tab is not rendered

- assets/i18n/ar.json
- assets/i18n/en.json
- assets/i18n/ro.json
[ch23781] Add second language (romanian).
> [ch23781] Additions for translations

- src_ts/components/pages/page-not-found.ts
> [ch22309]Fix intermittent lingering loading state

- .Dockerignore
- Dockerfile
> [ch24108]Build/deploy related refactoring

- package-lock.json
- package.json
[ch24283] moment.js is deprecated, time for an alternative
> [ch24283] moment.js is deprecated, time for an alternative

- src_ts/components/common/layout/filters/etools-filters.ts
- src_ts/components/pages/interventions/intervention-list.ts
> [ch24038]Clear all btn to clear filters also, not just their selected values

- src_ts/components/pages/interventions/intervention-list.ts
[ch24430] ePD: "Unicef" should be "UNICEF" across entire application
> [ch24430] ePD: "Unicef" should be "UNICEF" across entire application

- src_ts/components/common/layout/filters/etools-filters.ts
[ch24640] Clear all button is embossed and has an action state
> [ch24640] Clear all button is embossed and has an action state

- package-lock.json
- package.json
[ch24582]Navigation with tab in Calendar: days that are not visible should not be focusable
> [ch24582]Navigation with tab in Calendar: days that are not visible should not be focusable

- src_ts/components/common/layout/filters/etools-filters.ts
[ch24640] Clear all button is embossed and has an action state
> [ch24640] Clear all button focused style

- package-lock.json
- package.json
> [ch24448]update etools-table

- src_ts/components/app-shell/app-shell-styles.ts
- src_ts/components/app-shell/footer/page-footer.ts
- src_ts/components/app-shell/header/page-header-styles.ts
- src_ts/components/app-shell/menu/styles/nav-menu-styles.ts
- src_ts/components/common/layout/filters/etools-filters-styles.ts
- src_ts/components/common/layout/page-content-header/page-content-header.ts
- src_ts/components/styles/grid-layout-styles-lit.ts
> drop use of flex basis 0.000000001px

- package-lock.json
- package.json
- src_ts/components/app-shell/app-theme.ts
- src_ts/components/common/layout/filters/etools-filters-styles.ts
- src_ts/components/common/layout/filters/etools-filters.ts
- src_ts/components/common/toast-notifications/etools-toast.ts
- src_ts/components/pages/page-not-found.ts
- src_ts/components/styles/grid-layout-styles-lit.ts
> [ch24903] Fix lint errors

- index.html
- package-lock.json
- package.json
- polymer.json
- src_ts/config/config.ts
> [ch24812]focus-visible polyfill  for Safari

- src_ts/components/pages/interventions/intervention-list.ts
> [ch25176]Relabel IP Accepted&localize

- package-lock.json
- package.json
[ch25330] For numeric fields- select content on click/focus for easier editing
> [ch25330] For numeric fields- select content on click/focus for easier editing

- package-lock.json
- package.json
[ch25290] Multiselect Dropdown UX
> [ch25290] Multiselect Dropdown UX

- src_ts/components/app-shell/app-shell.ts
- src_ts/components/app-shell/app-theme.ts
- src_ts/components/app-shell/required-style-theme-arabic.ts
- src_ts/components/app-shell/required-style-theme.ts
- src_ts/components/styles/shared-styles-lit.ts
> [ch25508]Style fixes for rtl - label with required star

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/redux/actions/app.ts
- src_ts/routing/routes.ts
> [ch25910]Fix circular dependency in routing

- package-lock.json
- package.json
> [ch25921] Update etools-date-time

- package-lock.json
- package.json
[ch25949] Tweak UI for PD Activity dialog
> [ch25949] Tweak UI for PD Activity dialog

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/list/list-helper.ts
- src_ts/redux/actions/app.ts
- src_ts/redux/reducers/app.ts
> [ch25932]Update list on intervention status change

- polymer.json
- src_ts/components/app-shell/app-shell.ts
- src_ts/routing/component-lazy-load-config.ts
> [ch26224]ePD changes

- package-lock.json
- package.json
[ch26096] When datepicker opens, see if it can be scrolled into view
> [ch26096] When datepicker opens, see if it can be scrolled into view

- package-lock.json
- package.json
[ch25945] Effective and Efficient Programme Mgmt to have itemized costs
> [ch25945] Effective and Efficient Programme Mgmt to have itemized costs

- package-lock.json
- package.json
[ch26218] Restyle datepicker control
> [ch26218] Restyle datepicker control

- .gitmodules
- package-lock.json
- package.json
- src_ts/components/app-shell/app-shell.ts
- src_ts/components/pages/page-not-found.ts
> [ch26373]Update imports

- src_ts/components/pages/eface/eface-tab-pages/eface-tabs.ts
- src_ts/components/pages/eface/list/eface-list.ts
> [ch26415]Customizable title for the cancel-justification component

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/interventions-filters.ts
[ch26373]
TODO -update etools-modules-common submodule ref before merge
> [ch26373]Filters refactor

- .gitmodules
- package-lock.json
- package.json
- src_ts/components/app-shell/app-shell.ts
- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/interventions-filters.ts
> [ch26373]Use etools-modules-common package

- Accessibility-Guidelines.md
> [ch26587]Accessibility guidelines info

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/utils/debouncer.ts
> [ch26860] Add debouncer to list request

- tsconfig.json
> [ch26887] Map icons missing

- package-lock.json
- package.json
> [ch26861]Update common package

- src_ts/components/app-shell/app-shell.ts
- src_ts/redux/reducers/common-data.ts
> [ch26761] Add provided by to common data

- package-lock.json
- package.json
- src_ts/components/app-shell/app-shell.ts
- src_ts/components/common/toast-notifications/toast-notification-helper.ts
> [ch27247]Piwik tracking

- package-lock.json
- package.json
- src_ts/components/pages/interventions/intervention-list.ts
> [ch27130] Fix TsLint errors

- src_ts/components/app-shell/header/page-header.ts
- src_ts/config/config.ts
[ch27249] Dropdown option for Ro translations (used for testing) to not be available on prod
> [ch27249] Dropdown option for Ro translations (used for testing) to not be available on prod

- package-lock.json
- package.json
> [ch26841]Lit etools-info-tooltip

- package-lock.json
- package.json
> [ch27521]etools-table update

- index.html
- polymer.json
- push-manifest.json
- src_ts/app-shell.ts
- src_ts/components/common/toast-notifications/toast-notification-helper.ts
> [ch24682]Move app-shell

- package-lock.json
- package.json
[ch28050] Fund reservation related tooltip showing up when there is no Fund reservation
> [ch28050] Fund reservation related tooltip showing up when there is no Fund reservation

- package-lock.json
- package.json
[ch28044] Date picker validation is not reset on canceling the edit
> [ch28044] Date picker validation is not reset on canceling the edit

- package-lock.json
- package.json
> [ch26841] Etools upload migration

- package-lock.json
- package.json
[ch28302] Lit migration upload component: Signature &Dates issues
> [ch28302] Lit migration upload component: Signature &Dates issues

- package-lock.json
- package.json
- src_ts/app-shell.ts
- src_ts/components/user/user-actions.ts
> [ch27536]Redirect to pmp by user type

- assets/i18n/ar.json
- assets/i18n/en.json
- assets/i18n/ro.json
- src_ts/components/pages/interventions/intervention-list.ts
[ch28711] Handle 500 error on GET intervention list
> [ch28711] Handle 500 error on GET intervention list

- src_ts/redux/actions/app.ts
> [ch28795] Add route to editor page and back

- package-lock.json
- package.json
> [ch29607]Update etools-modules-common

- package-lock.json
- package.json
> [ch29745]Update etools-currency

- polymer.json
> [ch29824] Add all icons to build

- src_ts/components/app-shell/app-theme.ts
[ch29822]  Save btn focus is not enough to be just bold. needs better signifier
> [ch29822] Save btn focus is not enough to be just bold. needs better signifier

- package-lock.json
- package.json
> [ch29896] Fix dialog buttons focusing by tab

- src_ts/redux/actions/app.ts
- src_ts/redux/reducers/app.ts
> [ch29659] Split action to route_update and current_item_reset

- .circleci/config.yml
- package-lock.json
- package.json
[ch30429] [Editor] Refactor - extract reusable methods, templates
> [ch30429] [Editor] Refactor - extract reusable methods, templates

- src_ts/app-shell.ts
- src_ts/endpoints/endpoints-list.ts
- src_ts/redux/actions/common-data.ts
> [ch30674]Remove /api/v2/dropdowns/static/

- package-lock.json
- package.json
> [ch31182]etools-types updates

- src_ts/components/app-shell/header/page-header.ts
[ch31321] Improve the language dropdown
> [ch31321] Improve the language dropdown

- src_ts/app-shell.ts
- src_ts/components/app-shell/header/page-header.ts
- src_ts/components/user/user-actions.ts
- src_ts/components/utils/utils.ts
- src_ts/config/app-constants.ts
- src_ts/redux/actions/active-language.ts
- src_ts/redux/reducers/active-language.ts
[ch31363] [Intermittent] Selected (user) Language not displayed
> [ch31363] [Intermittent] Selected (user) Language not displayed

- src_ts/components/app-shell/header/page-header.ts
[ch31228] Investigate why translations don't work without page refresh on language change
> [ch31228] Investigate why translations don't work without page refresh on language change

- assets/i18n/ar.json
- assets/i18n/en.json
- assets/i18n/es.json
- assets/i18n/fr.json
- assets/i18n/pt.json
- assets/i18n/ro.json
- assets/i18n/ru.json
- src_ts/components/pages/interventions/intervention-list.ts
[ch31416] various ePD export options
> [ch31416] various ePD export options

- src_ts/app-shell.ts
> [ch32246]Flash of translation keys instead of text on page refresh/ Delay UI update until translation file is loaded

- src_ts/components/pages/interventions/intervention-list.ts
[ch32131] Unnecessary Toast error on navigating from details to list
> [ch32131] Unnecessary Toast error on navigating from details to list

- src_ts/components/pages/interventions/intervention-list.ts
[32335] URL and list results not updated correctly when deleting the search criteria
> [32335] URL and list results not updated correctly when deleting the search criteria

- package-lock.json
- package.json
- src_ts/components/pages/interventions/intervention-list.ts
[ch32237] PD list: adjust No results to display
> [ch32237] PD list: adjust No results to display

- package-lock.json
- package.json
[ch32471] Upload button translation at language change updates after refresh
> [ch32471] Upload button translation at language change updates after refresh

- .circleci/config.yml
- src_ts/redux/actions/app.ts
- src_ts/redux/reducers/app.ts
> [ch32460]Set comment mode timing

- src_ts/components/app-shell/header/page-header.ts
- src_ts/config/app-constants.ts
> [ch32445]Fix ro lang on page refresh

- package-lock.json
- package.json
[ch32652] Filters dropdown: scroll not working, you can only drag the bar
> [ch32652] Filters dropdown: scroll not working, you can only drag the bar

- package-lock.json
- package.json
[ch32712] Cannot close tooltips
> [ch32712] Cannot close tooltips

- package-lock.json
- src_ts/app-shell.ts
[ch32720] Uncaught TypeError: Cannot set properties of null (setting 'scrollTop')
> [ch32720] Uncaught TypeError: Cannot set properties of null (setting 'scrollTop')

- package-lock.json
- package.json
[ch32725] Tab navigation on dropdowns not working properly
> [ch32725] Tab navigation on dropdowns not working properly

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/interventions-filters.ts
[ch32968] Remove Budget owner filter in ePD
> [ch32968] Remove Budget owner filter in ePD

- assets/i18n/ar.json
- assets/i18n/en.json
- assets/i18n/es.json
- assets/i18n/fr.json
- assets/i18n/pt.json
- assets/i18n/ru.json
- src_ts/app-shell.ts
- src_ts/redux/actions/common-data.ts
- src_ts/redux/reducers/common-data.ts
[ch33014] Translations: Values not updated at language switch
> [ch33014] Translations: Values not updated at language switch

- src_ts/app-shell.ts
- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/redux/reducers/common-data.ts
[ch33064] Translations: Values not updated at language switch part II
> [ch33064] Translations: Values not updated at language switch part II

- package-lock.json
- package.json
[ch32793] Tab navigation: 13 tabs to skip the App selector and reach the Language dropdown
> [ch32793] Tab navigation: 13 tabs to skip the App selector and reach the Language dropdown

- package-lock.json
- package.json
> [ch33096]Issue in multi-dropdown, when clicking on the red x to unselect an item

- src_ts/components/app-shell/menu/app-menu.ts
[ch33275] Update knowledge base link and remove discussion and information
> [ch33275] Update knowledge base link and remove discussion and information

- src_ts/app-shell.ts
- src_ts/components/app-shell/header/page-header.ts
- src_ts/components/app-shell/menu/app-menu.ts
- src_ts/redux/actions/app.ts
- src_ts/redux/reducers/app.ts
> [ch33266]Remove Side-menu state from redux store

- package-lock.json
- package.json
[ch33265] Arabic: tooltip overlaps the upload button for the Supply items list
> [ch33265] Arabic: tooltip overlaps the upload button for the Supply items list

- package-lock.json
- package.json
[ch33183]  Uploads: File type validation goes away when you hit Save or is incorrectly kept when deleting the file
> [ch33183] Uploads: File type validation goes away when you hit Save or is incorrectly kept when deleting the file

- package-lock.json
- package.json
> [ch33404]Fix info icon click opening dropdown also

- package-lock.json
- package.json
> [ch33950]Update e-ajax

- src_ts/components/app-shell/app-theme.ts
[ch33917] Comments panel: On expand/collapse the comments panel header has corners
> [ch33917] Comments panel: On expand/collapse the comments panel header has corners

- src_ts/components/app-shell/header/countries-dropdown-styles.ts
[ch34297] Arabic translations: Adjust the Country and Organization selector
> [ch34297] Arabic translations: Adjust the Country and Organization selector

- index.html
> [ch34632]Shoelace dropdown - darker text color, font family

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/interventions-filters.ts
> [ch34779][Intermittent]Filters names not displayed correctly

- src_ts/components/pages/interventions/intervention-list.ts
- src_ts/components/pages/interventions/interventions-filters.ts
> [ch34779]Filters translation after lang change

- index.html
> [ch34901]Shoelace CSS vars update

- src_ts/components/pages/interventions/intervention-list.ts
[ch35074] Remove PMP Partners Export button, ePD list Export button
> [ch35074] Remove PMP Partners Export button, ePD list Export button

- package-lock.json
- package.json
- src_ts/app-shell.ts
- src_ts/components/app-shell/header/page-header.ts
[ch35140] Replace polymer app-layout components with Lit alternatives
> [ch35140] Replace polymer app-layout components with Lit alternatives

- src_ts/components/pages/interventions/intervention-list.ts
> [ch36680] error aborted

- src_ts/components/app-shell/header/countries-dropdown-styles.ts
- src_ts/components/app-shell/header/countries-dropdown.ts
- src_ts/components/app-shell/header/organizations-dropdown.ts
- src_ts/components/app-shell/header/page-header-styles.ts
- src_ts/components/app-shell/header/page-header.ts
> Header adjustments

- .eslintrc.json
- package-lock.json
- package.json
[ch37199] Update apps packages to avoid breakings from the new smob library
> [ch37199] Update apps packages to avoid breakings from the new smob library

- src_ts/components/app-shell/header/page-header.ts
[ch37388] ePD Side left menu is not working in mobile view
> [ch37388] ePD Side left menu is not working in mobile view

- .circleci/config.yml
- package-lock.json
- package.json
[ch39548] Etools-modules-common improvements
> [ch39548] Etools-modules-common improvements

- src_ts/components/pages/interventions/intervention-list.ts
[259691] Pagination issues and improvements
> [259691] Pagination issues and improvements
